name: Check and tag version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-and-tag:
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic:5.0.0
    env:
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
    steps:
      - uses: actions/checkout@v2
      - name: Check and tag version
        run: |
          /scripts/release-checks.sh --java --maven pom.xml
          source /scripts/common.sh
          version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
          tag_finalize_version $version
        shell: bash

