name: Check and tag version

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check-and-tag:
    runs-on: ubuntu-latest
    container: zepben/pipeline-basic:5.0.0
    env:
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      NEXUS_MAVEN_SNAPSHOT: ${{ secrets.NEXUS_MAVEN_SNAPSHOT }}
      NEXUS_MAVEN_RELEASE: ${{ secrets.NEXUS_MAVEN_RELEASE }}
      SLACK_NOTIFICATION: YES
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      CI_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Check and tag version
        run: |
          /scripts/release-checks.sh --java --maven pom.xml
          source /scripts/common.sh
          version=$(xmlstarlet pyx pom.xml | grep -v ^A | xmlstarlet p2x | xmlstarlet sel -t -v "/project/version")
          git remote rm origin
          remote="https://zepben-ci:${CI_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git config user.name "zepben-ci"
          git config user.email "admin.github@zepben.com"
          git remote add origin $remote
          git tag "v$version"
          git push --tags
          # tag_finalize_version $version
        shell: bash

