name: Release

on:
  push:
    tags:
      - v*
  repository_dispatch:
    types: [trigger-release]
  workflow_dispatch:


jobs:
  deploy-central:
    runs-on: ubuntu-latest
    container: zepben/pipeline-java-amazoncorretto:4.1.0
    env:
      ZEPBEN_GPG_KEY: ${{ secrets.ZEPBEN_GPG_KEY }}
      MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_KEY_PASSWORD: ${{ secrets.GPG_KEY_PASSWORD }}
      DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven

      - name: Maven deploy to Central
        run: |
          echo $ZEPBEN_GPG_KEY > zepben-gpg.key
          gpg2 --batch --import zepben-gpg.key
          mvn clean deploy -f pom.xml -s maven-settings.xml -P release,ossrh -Dserver.username=$OSSRH_USERNAME -Dserver.password=$OSSRH_PASSWORD -Dgpg.key.id=$GPG_KEY_ID -Dgpg.key.password=$GPG_KEY_PASSWORD
        shell: bash
